server:
  address: localhost
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/querydsl
    username: dsl
    password: super-dsl-pw

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate.SQL: debug






